---
- name: Add EPEL 6.8.
  shell: rpm -q epel-release-6-8 | grep -qw epel-release-6-8 || rpm -i http://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
  sudo: yes
  environment: proxy_env

- name: Install dependencies using yum.
  yum: name={{ item }} state=present
  sudo: yes
  with_items:
    - centos-release-SCL
    - libselinux-python
    - curl
    - python27
  environment: proxy_env

- name: Install pandoc.
  yum: name={{ item }} state=present
  sudo: yes
  with_items:
    - gcc
    - gcc-c++
    - pandoc
  environment: proxy_env

- name: Install rrdtool deps.
  yum: name={{ item }} state=present
  sudo: yes
  with_items:
    - glib
    - glib-devel
    - libxml2
    - libxml2-devel
    - libpng
    - libpng-devel
    - cairo
    - cairo-devel
    - pango
    - pango-devel
  environment: proxy_env

- name: Add Repoforge EL 6.
  shell: rpm -q rpmforge-release-0.5.3 | grep -qw rpmforge-release-0.5.3 || rpm -i http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
  sudo: yes
  environment: proxy_env

- name: Install rrdtool, rrdtool-devel.
  yum: name={{ item }} state=latest enablerepo=rpmforge-extras
  sudo: yes
  with_items:
    - rrdtool
    - rrdtool-devel

- name: Install pip with python2.7.
  shell: scl enable python27 "curl https://raw.githubusercontent.com/pypa/pip/master/contrib/get-pip.py | python -"
  sudo: yes
  environment: proxy_env

- name: Install ipython notebook (and deps) and python-rrdtool with pip2.7.
  shell: scl enable python27 'pip2.7 install {{ item }}'
  sudo: yes
  with_items:
    - pyzmq
    - tornado
    - jinja
    - ipython[notebook]
    - python-rrdtool
  environment: proxy_env
